---
# enable nginx as service
- name: apache_service_cluster_start
  service: { name: "{{ apache.servicename }}", enabled: yes }
  notify: [ 'apache start' ]

- name: apache start
  service: { name: "{{ apache.servicename }}", state: started }

# restrts nginx with new configuration
- name: apache restart
  service: { name : "{{ apache.servicename }}", state : restarted }
